services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/ssl/certs:/etc/ssl/certs
    networks:
      - web_net

networks:
  web_net: